sfmrabbit:
    image: rabbitmq@sha256:397382d2b222f3a298a6c74e93f348fb16f9a7fde2c02ba14122624d852daae3
    #RabbitMQ 3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - TZ=America/New_York
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmtwitterrestharvester:
    image: gwul/sfm-twitter-rest-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=America/New_York
        - DEBUG=True
sfmtwitterstreamharvester:
    image: gwul/sfm-twitter-stream-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    environment:
        - TZ=America/New_York
        - DEBUG=True
